// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/Sanaruca/condominio/internal/administracion/models/cuota/estadoproyecto"
	"github.com/Sanaruca/condominio/internal/administracion/models/deuda/estadodeuda"
	"github.com/Sanaruca/condominio/internal/pagos/types/metododepago"
	"github.com/Sanaruca/condominio/internal/pagos/types/moneda"
	"github.com/Sanaruca/condominio/internal/unidades/models/unidad/estadounidad"
)

type Cuota interface {
	IsCuota()
	GetID() string
	GetMonto() float64
	GetMes() int32
	GetAnio() int32
	GetRegistro() time.Time
	GetActualizacion() time.Time
	GetRecaudacion() *Recaudacion
}

type CuotaType interface {
	IsCuotaType()
}

type Paginable interface {
	IsPaginable()
}

type Sujeto interface {
	IsSujeto()
	GetID() string
	GetEmail() string
	GetTelefono() string
	GetCedula() string
	GetRegistro() time.Time
	GetActualizacion() time.Time
}

type Titular interface {
	IsTitular()
}

type Abono struct {
	Pago  string    `json:"pago"`
	Monto float64   `json:"monto"`
	Fecha time.Time `json:"fecha"`
}

type BooleanCondition struct {
	Eq *bool `json:"eq,omitempty"`
}

type CuotaEspecial struct {
	ID            string       `json:"id"`
	Monto         float64      `json:"monto"`
	Mes           int32        `json:"mes"`
	Anio          int32        `json:"anio"`
	Registro      time.Time    `json:"registro"`
	Actualizacion time.Time    `json:"actualizacion"`
	Detalles      *Proyecto    `json:"detalles"`
	Recaudacion   *Recaudacion `json:"recaudacion"`
}

func (CuotaEspecial) IsCuota()                          {}
func (this CuotaEspecial) GetID() string                { return this.ID }
func (this CuotaEspecial) GetMonto() float64            { return this.Monto }
func (this CuotaEspecial) GetMes() int32                { return this.Mes }
func (this CuotaEspecial) GetAnio() int32               { return this.Anio }
func (this CuotaEspecial) GetRegistro() time.Time       { return this.Registro }
func (this CuotaEspecial) GetActualizacion() time.Time  { return this.Actualizacion }
func (this CuotaEspecial) GetRecaudacion() *Recaudacion { return this.Recaudacion }

func (CuotaEspecial) IsCuotaType() {}

type CuotaFilter struct {
	ID    *StringCondition `json:"id,omitempty"`
	Monto *IntCondition    `json:"monto,omitempty"`
	And   []*CuotaFilter   `json:"and,omitempty"`
	Or    []*CuotaFilter   `json:"or,omitempty"`
	Not   *CuotaFilter     `json:"not,omitempty"`
}

type CuotaRegular struct {
	ID            string       `json:"id"`
	Monto         float64      `json:"monto"`
	Mes           int32        `json:"mes"`
	Anio          int32        `json:"anio"`
	Registro      time.Time    `json:"registro"`
	Actualizacion time.Time    `json:"actualizacion"`
	Recaudacion   *Recaudacion `json:"recaudacion"`
}

func (CuotaRegular) IsCuota()                          {}
func (this CuotaRegular) GetID() string                { return this.ID }
func (this CuotaRegular) GetMonto() float64            { return this.Monto }
func (this CuotaRegular) GetMes() int32                { return this.Mes }
func (this CuotaRegular) GetAnio() int32               { return this.Anio }
func (this CuotaRegular) GetRegistro() time.Time       { return this.Registro }
func (this CuotaRegular) GetActualizacion() time.Time  { return this.Actualizacion }
func (this CuotaRegular) GetRecaudacion() *Recaudacion { return this.Recaudacion }

func (CuotaRegular) IsCuotaType() {}

type Deuda struct {
	ID       string                    `json:"id"`
	Estado   estadodeuda.EstadoDeDeuda `json:"estado"`
	Cuota    string                    `json:"cuota"`
	Unidad   string                    `json:"unidad"`
	Monto    float64                   `json:"monto"`
	Deuda    float64                   `json:"deuda"`
	Abonos   []*Abono                  `json:"abonos,omitempty"`
	Registro time.Time                 `json:"registro"`
}

type Ente struct {
	ID            string    `json:"id"`
	RazonSocial   string    `json:"razon_social"`
	Email         string    `json:"email"`
	Telefono      string    `json:"telefono"`
	Cedula        string    `json:"cedula"`
	Representante *Persona  `json:"representante"`
	Registro      time.Time `json:"registro"`
	Actualizacion time.Time `json:"actualizacion"`
}

func (Ente) IsSujeto()                        {}
func (this Ente) GetID() string               { return this.ID }
func (this Ente) GetEmail() string            { return this.Email }
func (this Ente) GetTelefono() string         { return this.Telefono }
func (this Ente) GetCedula() string           { return this.Cedula }
func (this Ente) GetRegistro() time.Time      { return this.Registro }
func (this Ente) GetActualizacion() time.Time { return this.Actualizacion }

func (Ente) IsTitular() {}

type Gasto struct {
	ID            string    `json:"id"`
	Concepto      string    `json:"concepto"`
	Proveedor     string    `json:"proveedor"`
	Cuota         *string   `json:"cuota,omitempty"`
	Monto         float64   `json:"monto"`
	Moneda        string    `json:"moneda"`
	Tasa          float64   `json:"tasa"`
	Total         float64   `json:"total"`
	Fecha         time.Time `json:"fecha"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Registro      time.Time `json:"registro"`
	RegistradoPor string    `json:"registrado_por"`
}

func (Gasto) IsPaginable() {}

type GastoWithProveedor struct {
	ID            string        `json:"id"`
	Concepto      string        `json:"concepto"`
	Proveedor     *Proveedor    `json:"proveedor"`
	Cuota         *string       `json:"cuota,omitempty"`
	Monto         float64       `json:"monto"`
	Moneda        moneda.Moneda `json:"moneda"`
	Tasa          float64       `json:"tasa"`
	Total         float64       `json:"total"`
	Fecha         time.Time     `json:"fecha"`
	Descripcion   *string       `json:"descripcion,omitempty"`
	Registro      time.Time     `json:"registro"`
	RegistradoPor string        `json:"registrado_por"`
}

type IntCondition struct {
	Eq  *int32 `json:"eq,omitempty"`
	Gt  *int32 `json:"gt,omitempty"`
	Gte *int32 `json:"gte,omitempty"`
	Lt  *int32 `json:"lt,omitempty"`
	Lte *int32 `json:"lte,omitempty"`
}

type LoginCredentialsDto struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type ObtenerProveedoresDto struct {
	ID  *StringCondition         `json:"id,omitempty"`
	And []*ObtenerProveedoresDto `json:"and,omitempty"`
	Or  []*ObtenerProveedoresDto `json:"or,omitempty"`
	Not *ObtenerProveedoresDto   `json:"not,omitempty"`
}

type Paginated struct {
	Data  []Paginable `json:"data"`
	Total int32       `json:"total"`
	Page  int32       `json:"page"`
	Pages int32       `json:"pages"`
	Limit int32       `json:"limit"`
}

type PaginatedCuota struct {
	Data  []CuotaType `json:"data"`
	Total int32       `json:"total"`
	Page  int32       `json:"page"`
	Pages int32       `json:"pages"`
	Limit int32       `json:"limit"`
}

type PaginatedDeuda struct {
	Data  []*Deuda `json:"data"`
	Total int32    `json:"total"`
	Page  int32    `json:"page"`
	Pages int32    `json:"pages"`
	Limit int32    `json:"limit"`
}

type PaginatedGasto struct {
	Data  []*Gasto `json:"data"`
	Total int32    `json:"total"`
	Page  int32    `json:"page"`
	Pages int32    `json:"pages"`
	Limit int32    `json:"limit"`
}

type PaginatedGastoWithProveedor struct {
	Data  []*GastoWithProveedor `json:"data"`
	Total int32                 `json:"total"`
	Page  int32                 `json:"page"`
	Pages int32                 `json:"pages"`
	Limit int32                 `json:"limit"`
}

type PaginatedPago struct {
	Data  []*Pago `json:"data"`
	Total int32   `json:"total"`
	Page  int32   `json:"page"`
	Pages int32   `json:"pages"`
	Limit int32   `json:"limit"`
}

type PaginatedUnidad struct {
	Data  []*Unidad `json:"data"`
	Total int32     `json:"total"`
	Page  int32     `json:"page"`
	Pages int32     `json:"pages"`
	Limit int32     `json:"limit"`
}

type Paginator struct {
	Page  int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type Pago struct {
	ID             string                    `json:"id"`
	Unidad         string                    `json:"unidad"`
	Fecha          time.Time                 `json:"fecha"`
	Metodo         metododepago.MetodoDePago `json:"metodo"`
	Monto          float64                   `json:"monto"`
	Referencia     *string                   `json:"referencia,omitempty"`
	Moneda         moneda.Moneda             `json:"moneda"`
	Tasa           float64                   `json:"tasa"`
	Total          float64                   `json:"total"`
	Registro       time.Time                 `json:"registro"`
	RegistradoPor  string                    `json:"registrado_por"`
	Actualizacion  time.Time                 `json:"actualizacion"`
	ActualizadoPor string                    `json:"actualizado_por"`
	Destinado      float64                   `json:"destinado"`
	Disponible     float64                   `json:"disponible"`
}

type PagoFilter struct {
	Unidad *StringCondition `json:"unidad,omitempty"`
	And    []*PagoFilter    `json:"and,omitempty"`
	Or     []*PagoFilter    `json:"or,omitempty"`
	Not    *PagoFilter      `json:"not,omitempty"`
}

type Persona struct {
	ID            string    `json:"id"`
	Nombres       string    `json:"nombres"`
	Apellidos     string    `json:"apellidos"`
	Email         string    `json:"email"`
	Telefono      string    `json:"telefono"`
	Cedula        string    `json:"cedula"`
	Registro      time.Time `json:"registro"`
	Actualizacion time.Time `json:"actualizacion"`
}

func (Persona) IsSujeto()                        {}
func (this Persona) GetID() string               { return this.ID }
func (this Persona) GetEmail() string            { return this.Email }
func (this Persona) GetTelefono() string         { return this.Telefono }
func (this Persona) GetCedula() string           { return this.Cedula }
func (this Persona) GetRegistro() time.Time      { return this.Registro }
func (this Persona) GetActualizacion() time.Time { return this.Actualizacion }

func (Persona) IsTitular() {}

type Proveedor struct {
	ID            string    `json:"id"`
	Rif           string    `json:"rif"`
	Nombre        string    `json:"nombre"`
	Email         *string   `json:"email,omitempty"`
	Telefono      *string   `json:"telefono,omitempty"`
	Direccion     *string   `json:"direccion,omitempty"`
	CreadoEn      time.Time `json:"creado_en"`
	ActualizadoEn time.Time `json:"actualizado_en"`
}

type Proyecto struct {
	Titulo         string                          `json:"titulo"`
	Estado         estadoproyecto.EstadoDeProyecto `json:"estado"`
	Descripcion    string                          `json:"descripcion"`
	Justificacion  string                          `json:"justificacion"`
	FechaLimite    time.Time                       `json:"fecha_limite"`
	InteresPorMora float64                         `json:"interes_por_mora"`
	Registro       time.Time                       `json:"registro"`
	Actualizacion  time.Time                       `json:"actualizacion"`
}

type Query struct {
}

type Recaudacion struct {
	Moneda             moneda.Moneda `json:"moneda"`
	MontoEstimado      float64       `json:"monto_estimado"`
	MontoRecaudado     float64       `json:"monto_recaudado"`
	MontoPendiente     float64       `json:"monto_pendiente"`
	PagosAsociados     int32         `json:"pagos_asociados"`
	Unidades           int32         `json:"unidades"`
	UnidadesAplicadas  int32         `json:"unidades_aplicadas"`
	UnidadesSolventes  int32         `json:"unidades_solventes"`
	UnidadesPendientes int32         `json:"unidades_pendientes"`
}

type RegistrarGastoDto struct {
	Concepto  string        `json:"concepto"`
	Proveedor string        `json:"proveedor"`
	Monto     int32         `json:"monto"`
	Moneda    moneda.Moneda `json:"moneda"`
	Fecha     *time.Time    `json:"fecha,omitempty"`
}

type RegistrarGastoYProveedorDto struct {
	Concepto  string                 `json:"concepto"`
	Proveedor *RegistrarProveedorDto `json:"proveedor"`
	Monto     int32                  `json:"monto"`
	Moneda    moneda.Moneda          `json:"moneda"`
	Fecha     *time.Time             `json:"fecha,omitempty"`
}

type RegistrarPagoDto struct {
	Unidad     string                    `json:"unidad"`
	Fecha      *time.Time                `json:"fecha,omitempty"`
	Metodo     metododepago.MetodoDePago `json:"metodo"`
	Referencia string                    `json:"referencia"`
	Monto      int32                     `json:"monto"`
	Tasa       int32                     `json:"tasa"`
	Moneda     moneda.Moneda             `json:"moneda"`
}

type RegistrarProveedorDto struct {
	Rif       string  `json:"rif"`
	Nombre    string  `json:"nombre"`
	Email     string  `json:"email"`
	Telefono  string  `json:"telefono"`
	Direccion *string `json:"direccion,omitempty"`
}

type StringCondition struct {
	Eq    *string   `json:"eq,omitempty"`
	Like  *string   `json:"like,omitempty"`
	Regex *string   `json:"regex,omitempty"`
	In    []*string `json:"in,omitempty"`
}

type Tasa struct {
	Valor  float64 `json:"valor"`
	Fuente string  `json:"fuente"`
	Fecha  string  `json:"fecha"`
	Tipo   string  `json:"tipo"`
	Moneda string  `json:"moneda"`
}

type Unidad struct {
	ID              string                      `json:"id"`
	Codigo          string                      `json:"codigo"`
	Estado          estadounidad.EstadoDeUnidad `json:"estado"`
	TitularPrimario Titular                     `json:"titular_primario,omitempty"`
	Contacto        *Persona                    `json:"contacto,omitempty"`
	Deuda           float64                     `json:"deuda"`
	Wallet          float64                     `json:"wallet"`
}

type UnidadFilter struct {
	ID     *StringCondition `json:"id,omitempty"`
	Codigo *StringCondition `json:"codigo,omitempty"`
	Estado *StringCondition `json:"estado,omitempty"`
	And    []*UnidadFilter  `json:"and,omitempty"`
	Or     []*UnidadFilter  `json:"or,omitempty"`
	Not    *UnidadFilter    `json:"not,omitempty"`
}

type UnidadesTotales struct {
	TotalUnidades         int32   `json:"total_unidades"`
	UnidadesActivas       int32   `json:"unidades_activas"`
	UnidadesInhabitadas   int32   `json:"unidades_inhabitadas"`
	UnidadesExentas       int32   `json:"unidades_exentas"`
	UnidadesEnLitigio     int32   `json:"unidades_en_litigio"`
	UnidadesSuspendidas   int32   `json:"unidades_suspendidas"`
	UnidadesPreventa      int32   `json:"unidades_preventa"`
	UnidadesConPendientes int32   `json:"unidades_con_pendientes"`
	UnidadesSolventes     int32   `json:"unidades_solventes"`
	TotalPendiente        float64 `json:"total_pendiente"`
	TotalAsignado         float64 `json:"total_asignado"`
}
