// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/Sanaruca/condominio/internal/pagos/types/metododepago"
	"github.com/Sanaruca/condominio/internal/pagos/types/moneda"
)

type Paginable interface {
	IsPaginable()
}

type BooleanCondition struct {
	Eq *bool `json:"eq,omitempty"`
}

type Cuota struct {
	ID            string    `json:"id"`
	Monto         int32     `json:"monto"`
	Mes           int32     `json:"mes"`
	Anio          int32     `json:"anio"`
	Registro      time.Time `json:"registro"`
	Actualizacion time.Time `json:"actualizacion"`
}

func (Cuota) IsPaginable() {}

type CuotaFilter struct {
	ID    *StringCondition `json:"id,omitempty"`
	Monto *IntCondition    `json:"monto,omitempty"`
	And   []*CuotaFilter   `json:"and,omitempty"`
	Or    []*CuotaFilter   `json:"or,omitempty"`
	Not   *CuotaFilter     `json:"not,omitempty"`
}

type Gasto struct {
	ID            string    `json:"id"`
	Proveedor     string    `json:"proveedor"`
	Cuota         *string   `json:"cuota,omitempty"`
	Monto         int32     `json:"monto"`
	Moneda        string    `json:"moneda"`
	Tasa          int32     `json:"tasa"`
	Total         int32     `json:"total"`
	Fecha         time.Time `json:"fecha"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Registro      time.Time `json:"registro"`
	RegistradoPor string    `json:"registrado_por"`
}

func (Gasto) IsPaginable() {}

type IntCondition struct {
	Eq  *int32 `json:"eq,omitempty"`
	Gt  *int32 `json:"gt,omitempty"`
	Gte *int32 `json:"gte,omitempty"`
	Lt  *int32 `json:"lt,omitempty"`
	Lte *int32 `json:"lte,omitempty"`
}

type LoginCredentialsDto struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Paginated struct {
	Data  []Paginable `json:"data"`
	Total int32       `json:"total"`
	Page  int32       `json:"page"`
	Pages int32       `json:"pages"`
	Limit int32       `json:"limit"`
}

type Paginator struct {
	Page  int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type Pago struct {
	ID             string                    `json:"id"`
	Villa          int32                     `json:"villa"`
	Fecha          time.Time                 `json:"fecha"`
	Metodo         metododepago.MetodoDePago `json:"metodo"`
	Monto          int32                     `json:"monto"`
	Referencia     string                    `json:"referencia"`
	Moneda         moneda.Moneda             `json:"moneda"`
	Tasa           int32                     `json:"tasa"`
	Registro       time.Time                 `json:"registro"`
	RegistradoPor  string                    `json:"registrado_por"`
	Actualizacion  time.Time                 `json:"actualizacion"`
	ActualizadoPor string                    `json:"actualizado_por"`
	Destinado      int32                     `json:"destinado"`
	Cuenta         int32                     `json:"cuenta"`
}

type Proveedor struct {
	ID            string    `json:"id"`
	Rif           string    `json:"rif"`
	Nombre        string    `json:"nombre"`
	Email         *string   `json:"email,omitempty"`
	Telefono      *string   `json:"telefono,omitempty"`
	Direccion     *string   `json:"direccion,omitempty"`
	CreadoEn      time.Time `json:"creado_en"`
	ActualizadoEn time.Time `json:"actualizado_en"`
}

type Query struct {
}

type RegistrarGastoDto struct {
	Concepo   string        `json:"concepo"`
	Proveedor string        `json:"proveedor"`
	Monto     int32         `json:"monto"`
	Moneda    moneda.Moneda `json:"moneda"`
	Fecha     *time.Time    `json:"fecha,omitempty"`
}

type RegistrarGastoYProveedorDto struct {
	Concepo   string                 `json:"concepo"`
	Proveedor *RegistrarProveedorDto `json:"proveedor"`
	Monto     int32                  `json:"monto"`
	Moneda    moneda.Moneda          `json:"moneda"`
	Fecha     *time.Time             `json:"fecha,omitempty"`
}

type RegistrarPagoDto struct {
	Villa      int32                     `json:"villa"`
	Fecha      *time.Time                `json:"fecha,omitempty"`
	Metodo     metododepago.MetodoDePago `json:"metodo"`
	Referencia string                    `json:"referencia"`
	Monto      int32                     `json:"monto"`
	Tasa       int32                     `json:"tasa"`
	Moneda     moneda.Moneda             `json:"moneda"`
}

type RegistrarProveedorDto struct {
	Rif       string  `json:"rif"`
	Nombre    string  `json:"nombre"`
	Email     string  `json:"email"`
	Telefono  string  `json:"telefono"`
	Direccion *string `json:"direccion,omitempty"`
}

type StringCondition struct {
	Eq    *string   `json:"eq,omitempty"`
	Like  *string   `json:"like,omitempty"`
	Regex *string   `json:"regex,omitempty"`
	In    []*string `json:"in,omitempty"`
}

type Tasa struct {
	Valor  int32  `json:"valor"`
	Fuente string `json:"fuente"`
	Fecha  string `json:"fecha"`
	Tipo   string `json:"tipo"`
	Moneda string `json:"moneda"`
}
