// Code generated by AI; DO NOT EDIT WITHOUT REVIEW.
// This script injects PaginatedXxx types in GraphQL schemas based on @paginable directive.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const injection_template = `
# Code generated by tools/autopaginated/main.go
type Paginated%[1]s {
  data: [%[1]s!]!
  total: Int!
  page: Int!
  pages: Int!
  limit: Int!
}
`

func main() {
	projectRoot, err := findProjectRoot()
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	err = filepath.Walk(projectRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}

		if info.IsDir() {
			dirName := filepath.Base(path)
			switch dirName {
			case "node_modules", ".git", "vendor", "dist", "build", ".vscode", ".idea":
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".graphqls") {
			return nil
		}
		return injectPaginated(path)
	})

	if err != nil {
		fmt.Printf("Error en el proceso: %v\n", err)
	}
}

func injectPaginated(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	raw := string(content)

	re := regexp.MustCompile(`(?s)(type\s+(\w+)\s+@paginable\s*\{.*?\n\})`)

	newContent := re.ReplaceAllStringFunc(raw, func(match string) string {
		submatch := re.FindStringSubmatch(match)
		typeName := submatch[2]

		existingPattern := regexp.MustCompile(fmt.Sprintf(`(?s)# Code generated by tools/autopaginated/main.go\s*type Paginated%s\s*\{[^}]*\}`, typeName))
		if existingPattern.MatchString(raw) {
			return match
		}

		fmt.Printf("✓ Aplicando template a: %s (Paginated%s)\n", path, typeName)

		injected := fmt.Sprintf(injection_template, typeName)
		return match + injected
	})

	if newContent != raw {
		return os.WriteFile(path, []byte(newContent), 0644)
	}
	return nil
}

func findProjectRoot() (string, error) {
	curr, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(curr, "go.mod")); err == nil {
			return curr, nil
		}
		parent := filepath.Dir(curr)
		if parent == curr {
			return "", fmt.Errorf("go.mod no encontrado")
		}
		curr = parent
	}
}
