package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/usuarios/app/command"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.LoginCredentialsDto, error) {
	baseCtx, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	result, err := r.Usuarios.Commands.Login.Exec(baseCtx, command.LoginDTO{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return nil, err
	}
	return &model.LoginCredentialsDto{
		Token: result.Token,
	}, nil
}
