package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	"github.com/Sanaruca/condominio/internal/core/common"
	coreContext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerGastosSegunCuota is the resolver for the obtenerGastosSegunCuota field.
func (r *queryResolver) ObtenerGastosSegunCuota(ctx context.Context, cuotaID string, paginator *model.Paginator) (*model.Paginated, error) {
	baseCtx := ctx.Value(coreContext.BASE_CONTEXT_KEY).(coreContext.BaseContext)

	final_paginator := common.Paginator{}

	if paginator != nil {
		final_paginator.Page = int(paginator.Page)
		final_paginator.Limit = int(paginator.Limit)
	}

	result, err := r.Administracion.Queries.ObtenerGastosSegunCuota.Exec(baseCtx, query.ObtenerGastosSegunCuotaDTO{
		CuotaID:   cuotaID,
		Paginator: final_paginator,
	})
	if err != nil {
		return nil, err
	}

	data := make([]model.Paginable, len(result.Data))
	for i, gasto := range result.Data {
		data[i] = model.Gasto{
			ID:             gasto.ID,
			Proveedor:      gasto.Proveedor,
			Cuota:          gasto.Cuota,
			Monto:          int32(gasto.Monto),
			Moneda:         gasto.Moneda,
			Tasa:           int32(gasto.Tasa),
			Total:          int32(gasto.Total),
			Fecha:          gasto.Fecha,
			Descripcion:    gasto.Descripcion,
			Registro:       gasto.Registro,
			Actualizacion:  gasto.Actualizacion,
			RegistradoPor:  gasto.RegistradoPor,
			ActualizadoPor: gasto.ActualizadoPor,
		}
	}

	return &model.Paginated{
		Data:  data,
		Total: int32(result.Total),
		Page:  int32(result.Page),
		Pages: int32(result.Pages),
		Limit: int32(result.Limit),
	}, nil
}
