package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	"github.com/Sanaruca/condominio/internal/core/common"
	corefilter "github.com/Sanaruca/condominio/internal/core/common/filter"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerCuotas is the resolver for the obtenerCuotas field.
func (r *queryResolver) ObtenerCuotas(ctx context.Context, filter *model.CuotaFilter, paginator *model.Paginator) (*model.Paginated, error) {
	baseCtx := ctx.Value(corecontext.BASE_CONTEXT_KEY).(corecontext.BaseContext)

	// Convertir el filtro de GraphQL a corefilter.Node
	var final_filter corefilter.Clause
	var err error

	// 1. Solo Parseamos en la capa de transporte (traducción de struct GraphQL a AST)
	if filter != nil {
		final_filter, err = corefilter.Parse(filter)
		if err != nil {
			// Fallamos rápido si el input no se puede ni siquiera transformar en árbol
			return nil, err
		}
	}

	final_paginator := common.Paginator{}
	if paginator != nil {
		final_paginator.Page = int(paginator.Page)
		final_paginator.Limit = int(paginator.Limit)
	}

	// 2. Pasamos el AST puro al caso de uso
	result, err := r.Administracion.Queries.ObtenerCuotas.Exec(baseCtx, query.ObtenerCuotasDTO{
		Filter:    final_filter,
		Paginator: final_paginator,
	})
	if err != nil {
		return nil, err
	}

	data := make([]model.Paginable, len(result.Data))

	for i, cuota := range result.Data {

		data[i] = model.Cuota{
			ID:            cuota.ID,
			Monto:         int32(cuota.Monto),
			Mes:           int32(cuota.Mes),
			Anio:          int32(cuota.Anio),
			Registro:      cuota.Registro,
			Actualizacion: cuota.Actualizacion,
		}

	}

	return &model.Paginated{
		Data:  data,
		Total: int32(result.Total),
		Page:  int32(result.Page),
		Pages: int32(result.Pages),
		Limit: int32(result.Limit),
	}, nil
}
