package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/model"
)

// ObtenerCuotas is the resolver for the obtenerCuotas field.
func (r *queryResolver) ObtenerCuotas(ctx context.Context, filter *model.CuotaFilter, paginator *model.Paginator) (*model.Paginated, error) {
	panic(fmt.Errorf("not implemented: ObtenerCuotas - obtenerCuotas"))
}
