package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/pagos/app/command"
)

// RegistrarPago is the resolver for the registrarPago field.
func (r *mutationResolver) RegistrarPago(ctx context.Context, input model.RegistrarPagoDto) (bool, error) {
	adminCtx, err := corecontext.Wrap(ctx).AsAdmin()
	if err != nil {
		return false, err
	}

	_, err = r.Pagos.Commands.RegistrarPago.Exec(adminCtx, command.RegistrarPagoDTO{
		Villa:      int(input.Villa),
		Fecha:      input.Fecha,
		Metodo:     input.Metodo,
		Referencia: &input.Referencia,
		Monto:      int(input.Monto),
		Tasa:       int(input.Tasa),
		Moneda:     input.Moneda,
	})

	if err != nil {
		return false, err
	}

	return true, nil
}
