package envirotment

import "os"

const (
	SECRET_KEY        = "SECRET_KEY"
	MAIL_PORT         = "MAIL_PORT"
	MAIL_HOST         = "MAIL_HOST"
	MAIL_FROM_ADDRESS = "MAIL_FROM_ADDRESS"
	MAIL_PASSWORD     = "MAIL_PASSWORD"

	// DATABASE

	DATABASE_HOST     = "DATABASE_HOST"
	DATABASE_USER     = "DATABASE_USER"
	DATABASE_PASSWORD = "DATABASE_PASSWORD"
	DATABASE_PORT     = "DATABASE_PORT"
	DATABASE_DATABASE = "DATABASE_DATABASE"
	DATABASE_URL      = "DATABASE_URL"
)

func GetSecretKey() string {
	return os.Getenv(SECRET_KEY)
}
