// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/Sanaruca/condominio/internal/administracion/types/tipodecuota"
	"github.com/Sanaruca/condominio/internal/pagos/types/metododepago"
	"github.com/Sanaruca/condominio/internal/pagos/types/moneda"
)

type LoginCredentialsDto struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Pago struct {
	ID             string                    `json:"id"`
	Villa          int32                     `json:"villa"`
	Fecha          time.Time                 `json:"fecha"`
	Metodo         metododepago.MetodoDePago `json:"metodo"`
	Monto          int32                     `json:"monto"`
	Referencia     string                    `json:"referencia"`
	Moneda         moneda.Moneda             `json:"moneda"`
	Tasa           int32                     `json:"tasa"`
	Registro       time.Time                 `json:"registro"`
	RegistradoPor  string                    `json:"registrado_por"`
	Actualizacion  time.Time                 `json:"actualizacion"`
	ActualizadoPor string                    `json:"actualizado_por"`
	Destinado      int32                     `json:"destinado"`
	Cuenta         int32                     `json:"cuenta"`
}

type Query struct {
}

type RegistrarCuotaDto struct {
	Mes   int32                   `json:"mes"`
	Anio  int32                   `json:"anio"`
	Monto int32                   `json:"monto"`
	Tipo  tipodecuota.TipoDeCuota `json:"tipo"`
}
