package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	cc "github.com/Sanaruca/condominio/internal/core/context"
)

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaEspecialResolver) Recaudacion(ctx context.Context, obj *model.CuotaEspecial) (*model.Recaudacion, error) {
	baseCtx, err := cc.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	recaudacion, err := r.Administracion.Queries.ObtenerRecaudacion.Exec(baseCtx, query.ObtenerRecaudacionDTO{
		CuotaID: obj.ID,
	})

	if err != nil {
		return nil, err
	}

	if recaudacion == nil {
		return nil, nil
	}

	model := model.RecaudacionFromDomain(*recaudacion)

	return &model, nil
}

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaRegularResolver) Recaudacion(ctx context.Context, obj *model.CuotaRegular) (*model.Recaudacion, error) {
	baseCtx, err := cc.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	recaudacion, err := r.Administracion.Queries.ObtenerRecaudacion.Exec(baseCtx, query.ObtenerRecaudacionDTO{
		CuotaID: obj.ID,
	})

	if err != nil {
		return nil, err
	}

	if recaudacion == nil {
		return nil, nil
	}

	model := model.RecaudacionFromDomain(*recaudacion)

	return &model, nil
}

// CuotaEspecial returns CuotaEspecialResolver implementation.
func (r *Resolver) CuotaEspecial() CuotaEspecialResolver { return &cuotaEspecialResolver{r} }

// CuotaRegular returns CuotaRegularResolver implementation.
func (r *Resolver) CuotaRegular() CuotaRegularResolver { return &cuotaRegularResolver{r} }

type cuotaEspecialResolver struct{ *Resolver }
type cuotaRegularResolver struct{ *Resolver }
