package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	"github.com/Sanaruca/condominio/internal/core/common"
	"github.com/Sanaruca/condominio/internal/core/common/filter"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	finanzasQuery "github.com/Sanaruca/condominio/internal/finanzas/app/query"
	"github.com/Sanaruca/condominio/internal/finanzas/models/operacion"
)

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaEspecialResolver) Recaudacion(ctx context.Context, obj *model.CuotaEspecial) (*model.Recaudacion, error) {
	return resolverObtenerRecaudacion(ctx, r.Resolver, obj.ID)
}

// Gastos is the resolver for the gastos field.
func (r *cuotaEspecialResolver) Gastos(ctx context.Context, obj *model.CuotaEspecial) ([]model.GastoType, error) {
	return resolverObtenerGastos(ctx, r.Resolver, obj.GetID())
}

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaRegularResolver) Recaudacion(ctx context.Context, obj *model.CuotaRegular) (*model.Recaudacion, error) {
	return resolverObtenerRecaudacion(ctx, r.Resolver, obj.ID)
}

// Gastos is the resolver for the gastos field.
func (r *cuotaRegularResolver) Gastos(ctx context.Context, obj *model.CuotaRegular) ([]model.GastoType, error) {
	return resolverObtenerGastos(ctx, r.Resolver, obj.GetID())
}

func resolverObtenerRecaudacion(ctx context.Context, r *Resolver, cuotaID string) (*model.Recaudacion, error) {
	baseCtx, err := cc.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	recaudacion, err := r.Administracion.Queries.ObtenerRecaudacion.Exec(baseCtx, query.ObtenerRecaudacionDTO{
		CuotaID: cuotaID,
	})
	if err != nil {
		return nil, err
	}

	if recaudacion == nil {
		return nil, nil
	}

	result := model.RecaudacionFromDomain(*recaudacion)
	return &result, nil
}

func resolverObtenerGastos(ctx context.Context, r *Resolver, cuotaID string) ([]model.GastoType, error) {
	base, err := cc.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	ftr := filter.NewFilter[operacion.GastoBase](map[string]any{
		"cuota": map[string]any{
			"eq": cuotaID,
		},
	})

	gastos, err := r.Transacciones.Queries.ObtenerGastos.Exec(base, finanzasQuery.ObtenerGastosDTO{
		// TODO: estar atento al limite
		Paginator: common.Paginator{Limit: 100},
		Filter:    ftr,
	})
	if err != nil {
		return nil, err
	}

	data := make([]model.GastoType, len(gastos.Data))
	for i, gasto := range gastos.Data {
		data[i] = model.GastoTypeFromDomain(gasto)
	}

	return data, nil
}

// CuotaEspecial returns CuotaEspecialResolver implementation.
func (r *Resolver) CuotaEspecial() CuotaEspecialResolver { return &cuotaEspecialResolver{r} }

// CuotaRegular returns CuotaRegularResolver implementation.
func (r *Resolver) CuotaRegular() CuotaRegularResolver { return &cuotaRegularResolver{r} }

type cuotaEspecialResolver struct{ *Resolver }
type cuotaRegularResolver struct{ *Resolver }
