package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/unidades/app/query"
)

// ObtenerUnidades is the resolver for the obtenerUnidades field.
func (r *queryResolver) ObtenerUnidades(ctx context.Context, filter *model.UnidadFilter, paginator *model.Paginator) (*model.PaginatedUnidad, error) {
	baseCtx, err := cc.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	unidades, err := r.Unidades.Queries.ObtenerUnidades.Exec(baseCtx, query.ObtenerUnidadesDTO{
		Paginator: paginator.ToDomainPaginator(),
		Filter:    filter.ToFilter(),
	})

	if err != nil {
		return nil, err
	}

	data := make([]*model.Unidad, len(unidades.Data))
	for i, unidad := range unidades.Data {
		data[i] = model.UnidadFromDomain(unidad)
	}

	return &model.PaginatedUnidad{
		Data:  data,
		Total: int32(unidades.Total),
		Page:  int32(unidades.Page),
		Pages: int32(unidades.Pages),
		Limit: int32(unidades.Limit),
	}, nil
}
