package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	database "github.com/Sanaruca/condominio/internal/shared/adapters/gorm"
	"gorm.io/gorm"
)

// ObtenerResumenUnidades is the resolver for the obtenerResumenUnidades field.
func (r *queryResolver) ObtenerResumenUnidades(ctx context.Context) (*model.UnidadesResumen, error) {
	result, err := gorm.G[database.ResumenUnidades](r.db).Take(ctx)

	if err != nil {
		return nil, err
	}

	return &model.UnidadesResumen{
		TotalUnidades:         int32(result.TotalUnidades),
		UnidadesActivas:       int32(result.UnidadesActivas),
		UnidadesInhabitadas:   int32(result.UnidadesInhabitadas),
		UnidadesExentas:       int32(result.UnidadesExentas),
		UnidadesEnLitigio:     int32(result.UnidadesEnLitigio),
		UnidadesSuspendidas:   int32(result.UnidadesSuspendidas),
		UnidadesPreventa:      int32(result.UnidadesPreventa),
		UnidadesConPendientes: int32(result.UnidadesConPendientes),
		UnidadesSolventes:     int32(result.UnidadesSolventes),
		TotalPendiente:        r.qf.Assemble(int64(result.TotalPendiente)).Float(),
		TotalAsignado:         r.qf.Assemble(int64(result.TotalAsignado)).Float(),
	}, nil
}
