package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/pagos/app/query"
)

// ObtenerPagos is the resolver for the obtenerPagos field.
func (r *queryResolver) ObtenerPagos(ctx context.Context, filter *model.PagoFilter, paginator *model.Paginator) (*model.PaginatedPago, error) {
	bc, err := cc.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	fltr := filter.ToFilter()

	pagos, err := r.Pagos.Queries.ObtenerPagos.Exec(bc, query.ObtenerPagosDTO{
		Paginator: paginator.ToDomainPaginator(),
		Filter:    &fltr,
	})

	if err != nil {
		return nil, err
	}

	data := make([]*model.Pago, len(pagos.Data))

	for i, p := range pagos.Data {
		data[i] = model.PagoFromDomain(p)
	}

	return &model.PaginatedPago{
		Data:  data,
		Total: int32(pagos.Total),
		Page:  int32(pagos.Page),
		Pages: int32(pagos.Pages),
		Limit: int32(pagos.Limit),
	}, nil
}
