package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"

	"github.com/Sanaruca/condominio/graph/model"
)

// ObtenerTasa is the resolver for the obtenerTasa field.
func (r *queryResolver) ObtenerTasa(ctx context.Context) (*model.Tasa, error) {
	ved, err := r.Sistema.Queries.ObtenerTasa.Exec(ctx, nil)

	if err != nil {
		return nil, err
	}

	return &model.Tasa{
		Valor:  int32(ved),
		Fuente: "dolarapi",
		Fecha:  time.Now().Format("2006-01-02"),
		Tipo:   "oficial",
		Moneda: "VES",
	}, nil
}
