package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/unidades/app/query"
)

// ObtenerUnidad is the resolver for the obtenerUnidad field.
func (r *queryResolver) ObtenerUnidad(ctx context.Context, id string) (*model.Unidad, error) {
	return r.resolverUnidadBase(ctx, id, r.Unidades.Queries.ObtenerUnidad)
}

func (r *queryResolver) ObtenerUnidadPorCodigo(ctx context.Context, codigo string) (*model.Unidad, error) {
	return r.resolverUnidadBase(ctx, codigo, r.Unidades.Queries.ObtenerUnidadPorCodigo)
}

// --- Función Auxiliar Privada ---

func (r *queryResolver) resolverUnidadBase(
	ctx context.Context,
	searchID string,
	handler query.ObtenerUnidad, // O el tipo de interfaz que compartan
) (*model.Unidad, error) {

	bc, err := cc.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	res, err := handler.Exec(bc, query.ObtenerUnidadDTO{SearchID: searchID})
	if err != nil {
		return nil, err
	}

	if res == nil {
		return nil, nil
	}

	return model.UnidadFromDomain(*res), nil
}
