package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/core"
	m "github.com/Sanaruca/condominio/internal/core/common/mes"
)

// ObtenerTasa is the resolver for the obtenerTasa field.
// El servicio de tasa de cambio está desconectado temporalmente (deuda técnica).
func (r *queryResolver) ObtenerTasa(ctx context.Context, anio *int32, mes *m.Mes, dia *int32) (*model.Tasa, error) {
	return nil, core.WrapError(errors.New("el servicio de tasa de cambio está desactivado"))
}
