package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerProveedores is the resolver for the obtenerProveedores field.
func (r *queryResolver) ObtenerProveedores(ctx context.Context, filter *model.ObtenerProveedoresDto) ([]*model.Proveedor, error) {
	adminCtx, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	dto := &query.ObtenerProveedoresDTO{
		Filter: filter.ToFilter(),
	}

	proveedores, err := r.Administracion.Queries.ObtenerProveedores.Exec(adminCtx, dto)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Proveedor, len(proveedores))
	for i, p := range proveedores {
		email := p.Email().String()
		telefono := p.Telefono().String()
		result[i] = &model.Proveedor{
			ID:            p.ID(),
			Rif:           p.Rif().String(),
			Nombre:        p.Nombre(),
			Email:         &email,
			Telefono:      &telefono,
			Direccion:     p.Direccion(),
			CreadoEn:      p.CreadoEn(),
			ActualizadoEn: p.ActualizadoEn(),
		}
	}

	return result, nil
}
