package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/loaders"
	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/core"
	gormAdapter "github.com/Sanaruca/condominio/internal/core/adapters/gorm"
	"github.com/Sanaruca/condominio/internal/core/common"
	"github.com/Sanaruca/condominio/internal/core/common/filter"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/core/lib/logger"
	database "github.com/Sanaruca/condominio/internal/shared/adapters/gorm"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// ObtenerOperaciones is the resolver for the obtenerOperaciones field.
func (r *queryResolver) ObtenerOperaciones(ctx context.Context, filtro *model.OperacionFilter, paginador *model.Paginator) (*model.PaginatedOperacion, error) {
	admin, err := cc.Wrap(ctx).AsAdmin()

	if err != nil {
		return nil, err
	}

	ftr, ferr := filter.Parse(filtro)

	if ferr != nil {
		return nil, err
	}

	paginator := paginador.ToDomainPaginator()

	rows, gerr := gorm.G[database.Operacion](r.db).
		Scopes(gormAdapter.GFilter(ftr), gormAdapter.GPaginate(paginator)).
		Joins(clause.LeftJoin.Association("Unidad"), nil).
		Joins(clause.LeftJoin.Association("Proveedor"), nil).
		Order(fmt.Sprintf("%s.fecha DESC", new(database.Operacion).TableName())).
		Find(admin)

	if gerr != nil {
		return nil, err
	}

	total, gerr := gorm.G[database.Operacion](r.db).Count(ctx, "id")

	if gerr != nil {
		return nil, err
	}

	data := make([]model.OperacionType, len(rows))

	for i, op := range rows {

		var operacion model.OperacionType

		if op.Tipo.DEBITO() {
			if op.Rol.Proveedor() {

				proveedor := new(model.Proveedor)

				if op.Proveedor != nil {

					p := op.Proveedor

					proveedor = &model.Proveedor{
						ID:            p.ID,
						Rif:           p.RIF,
						Nombre:        p.Nombre,
						Email:         &p.Email,
						Telefono:      &p.Telefono,
						Direccion:     p.Direccion,
						CreadoEn:      p.Registro,
						ActualizadoEn: p.Actualizacion,
					}

				} else {
					logger.ErrorCtx(ctx, nil, "Proveedor no asignado a una operacion de rol 'Proveedor'", "operacion.id", op.ID, "operacion.proveedor_id", op.ProveedorID)
				}

				operacion = model.GastoAProveedor{
					Operacion:     op.ID,
					Transaccion:   new(string),
					Cuota:         new(string),
					Fecha:         op.Fecha,
					Concepto:      op.Concepto,
					Monto:         r.qf.Assemble(int64(op.Monto)).Float(),
					Moneda:        op.Moneda,
					Total:         r.qf.Assemble(int64(op.Total)).Float(),
					Metodo:        op.Metodo,
					Tasa:          r.qf.Assemble(int64(op.Tasa)).Float(),
					RegistradoPor: op.RegistradoPor,
					Registro:      op.Registro,
					Proveedor:     proveedor,
				}
			} else if op.Rol.Condominio() {
				operacion = model.GastoACondominio{
					Operacion:     op.ID,
					Transaccion:   new(string),
					Cuota:         op.Cuota,
					Fecha:         op.Fecha,
					Concepto:      op.Concepto,
					Monto:         r.qf.Assemble(int64(op.Monto)).Float(),
					Moneda:        op.Moneda,
					Total:         r.qf.Assemble(int64(op.Total)).Float(),
					Metodo:        op.Metodo,
					Tasa:          r.qf.Assemble(int64(op.Tasa)).Float(),
					RegistradoPor: op.RegistradoPor,
					Registro:      op.Registro,
				}
			} else {
				logger.ErrorCtx(ctx, nil, "Tipo de gasto no soportado o indeterminado", "operacion.tipo", op.Tipo, "operacion.rol", op.Rol)
			}
		} else if op.Tipo.CREDITO() {

			if op.UnidadCodigo == nil {
				logger.FatalCtx(ctx, nil, `Operacion de "CREDITO" (Pago) se encuentra sin Unidad registrada`, "operacion.id", op.ID)
				return nil, core.ErrInternal
			}

			unidadIdentifiers, err := loaders.GetUnidadID(ctx, *op.UnidadCodigo)

			if err != nil {
				return nil, err
			}

			operacion = model.Pago{
				Operacion:     op.ID,
				Unidad:        unidadIdentifiers,
				Fecha:         op.Fecha,
				Concepto:      op.Concepto,
				Monto:         r.qf.Assemble(int64(op.Monto)).Float(),
				Moneda:        op.Moneda,
				Metodo:        op.Metodo,
				Tasa:          r.qf.Assemble(int64(op.Tasa)).Float(),
				RegistradoPor: op.RegistradoPor,
				Registro:      op.Registro,
				Total:         r.qf.Assemble(int64(op.Total)).Float(),
			}

		}

		data[i] = operacion
	}

	operaciones := common.NewPaginated(data, int(total), paginator)

	return &model.PaginatedOperacion{
		Data:  operaciones.Data,
		Total: int32(operaciones.Total),
		Page:  int32(operaciones.Page),
		Pages: int32(operaciones.Pages),
		Limit: int32(operaciones.Limit),
	}, nil
}
