package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerVillasTotales is the resolver for the obtenerVillasTotales field.
func (r *queryResolver) ObtenerVillasTotales(ctx context.Context) (*model.VillasTotales, error) {
	baseCtx, err := corecontext.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	result, err := r.Administracion.Queries.ObtenerVillasTotales.Exec(
		baseCtx,
		struct{}{},
	)

	if err != nil {
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	return &model.VillasTotales{
		TotalVillas:         int32(result.TotalVillas),
		VillasActivas:       int32(result.VillasActivas),
		VillasInhabitadas:   int32(result.VillasInhabitadas),
		VillasExentas:       int32(result.VillasExentas),
		VillasEnLitigio:     int32(result.VillasEnLitigio),
		VillasSuspendidas:   int32(result.VillasSuspendidas),
		VillasPreventa:      int32(result.VillasPreventa),
		VillasConPendientes: int32(result.VillasConPendientes),
		VillasSolventes:     int32(result.VillasSolventes),
		TotalPendiente:      result.TotalPendiente.Float(),
		TotalAsignado:       result.TotalAsignado.Float(),
	}, nil
}
