package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// TODO: ObtenerGastos is the resolver for the obtenerGastos field.
func (r *queryResolver) ObtenerGastos(ctx context.Context, paginator *model.Paginator) (*model.PaginatedGastoWithProveedor, error) {
	baseContext, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	gastos, err := r.Administracion.Queries.ObtenerGastos.Exec(baseContext, query.ObtenerGastosDTO{
		Paginator: paginator.ToDomainPaginator(),
	})

	if err != nil {
		return nil, err
	}

	// proveedores := core.NewSetFromSlice(gastos.Data, func(it gasto.Gasto) string {
	// 	return it.Proveedor()
	// })

	// proveedores_data, err := r.Administracion.Queries.ObtenerProveedores.Exec(baseContext, query.ObtenerProveedoresDTO{})

	return &model.PaginatedGastoWithProveedor{
		// Data:  ,
		Total: int32(gastos.Total),
		Page:  int32(gastos.Page),
		Pages: int32(gastos.Pages),
		Limit: int32(gastos.Limit),
	}, nil
}
