package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerCuota is the resolver for the obtenerCuota field.
func (r *queryResolver) ObtenerCuota(ctx context.Context, id string) (model.CuotaType, error) {
	baseCtx, err := corecontext.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}
	cuota, err := r.Administracion.Queries.ObtenerCuota.Exec(
		baseCtx,
		query.ObtenerCuotaDTO{ID: id},
	)

	if err != nil {
		return nil, err
	}

	return model.CuotaTypeFromDomain(cuota), nil
}
