package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerUnidadesEstadisticas is the resolver for the obtenerUnidadesEstadisticas field.
func (r *queryResolver) ObtenerUnidadesEstadisticas(ctx context.Context) (*model.UnidadesTotales, error) {
	bc, err := cc.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	estadisticas, err := r.Unidades.Queries.ObtenerEstadisticas.Exec(bc, nil)

	if err != nil {
		return nil, err
	}

	return model.UnidadesTotalesFromDomain(*estadisticas), nil
}
