package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	cc "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerDeudores is the resolver for the obtenerDeudores field.
func (r *queryResolver) ObtenerDeudores(ctx context.Context, filter *model.DeudaFilter, paginate *model.Paginator) (*model.PaginatedDeuda, error) {
	base, err := cc.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	ftr := filter.ToFilter()

	deudores, err := r.Administracion.Queries.ObtenerDeudores.Exec(base, query.ObtenerDeudoresDTO{
		Paginator: paginate.ToDomainPaginator(),
		Filter:    &ftr,
	})

	if err != nil {
		return nil, err
	}

	data := make([]*model.Deuda, len(deudores.Data))

	for i, d := range deudores.Data {
		data[i] = model.DeudaFromDomain(d.Deuda, d.Titular)
	}

	return &model.PaginatedDeuda{
		Data:  data,
		Total: int32(deudores.Total),
		Page:  int32(deudores.Page),
		Pages: int32(deudores.Pages),
		Limit: int32(deudores.Limit),
	}, nil
}
