package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
)

// ObtenerUnidad is the resolver for the obtenerUnidad field.
func (r *queryResolver) ObtenerUnidad(ctx context.Context, id string) (*model.Unidad, error) {
	return r.resolverUnidadBase(ctx, id, r.Unidades.Queries.ObtenerUnidad)
}

// ObtenerUnidadPorCodigo is the resolver for the obtenerUnidadPorCodigo field.
func (r *queryResolver) ObtenerUnidadPorCodigo(ctx context.Context, codigo string) (*model.Unidad, error) {
	return r.resolverUnidadBase(ctx, codigo, r.Unidades.Queries.ObtenerUnidadPorCodigo)
}
