package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
)

// ObtenerDeudasDeUnaUnidad is the resolver for the obtenerDeudasDeUnaUnidad field.
func (r *queryResolver) ObtenerDeudasDeUnaUnidad(ctx context.Context, id string, paginator *model.Paginator) (*model.PaginatedDeuda, error) {
	return r.resolverDeudasBase(ctx, id, paginator, r.Unidades.Queries.ObtenerDeudasDeUnaUnidad)
}

// ObtenerDeudasDeUnaUnidadPorCodigo is the resolver for the obtenerDeudasDeUnaUnidadPorCodigo field.
func (r *queryResolver) ObtenerDeudasDeUnaUnidadPorCodigo(ctx context.Context, codigo string, paginator *model.Paginator) (*model.PaginatedDeuda, error) {
	return r.resolverDeudasBase(ctx, codigo, paginator, r.Unidades.Queries.ObtenerDeudasDeUnaUnidadPorCodigo)
}
