package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerGastos is the resolver for the obtenerGastos field.
func (r *queryResolver) ObtenerGastos(ctx context.Context, paginator *model.Paginator) (*model.PaginatedGasto, error) {
	baseContext, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	gastos, err := r.Administracion.Queries.ObtenerGastos.Exec(baseContext, query.ObtenerGastosDTO{
		Paginator: paginator.ToDomainPaginator(),
	})

	if err != nil {
		return nil, err
	}

	data := make([]*model.Gasto, len(gastos.Data))

	for i, gasto := range gastos.Data {
		data[i] = model.GastoFromDomain(gasto)
	}

	return &model.PaginatedGasto{
		Data:  data,
		Total: int32(gastos.Total),
		Page:  int32(gastos.Page),
		Pages: int32(gastos.Pages),
		Limit: int32(gastos.Limit),
	}, nil
}
