package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/model"
)

// ObtenerDeudas is the resolver for the obtenerDeudas field.
func (r *queryResolver) ObtenerDeudas(ctx context.Context, filter *model.DeudaFilter, paginate *model.Paginator) (*model.PaginatedDeuda, error) {
	panic(fmt.Errorf("not implemented: ObtenerDeudas - obtenerDeudas"))
}
