package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/transacciones/app/query"
)

// ObtenerMovimientos is the resolver for the obtenerMovimientos field.
func (r *queryResolver) ObtenerMovimientos(ctx context.Context, paginator *model.Paginator, filter *model.TransaccionFilter) (*model.PaginatedTransaccion, error) {
	bc, err := cc.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	fltr := filter.ToFilter()

	result, err := r.Transacciones.Queries.ObtenerMovimientos.Exec(bc, query.ObtenerMovimientosDTO{
		Paginator: paginator.ToDomainPaginator(),
		Filter:    &fltr,
	})
	if err != nil {
		return nil, err
	}

	data := make([]*model.Transaccion, len(result.Data))
	for i, t := range result.Data {
		data[i] = model.TransaccionFromDomain(t)
	}

	return &model.PaginatedTransaccion{
		Data:  data,
		Total: int32(result.Total),
		Page:  int32(result.Page),
		Pages: int32(result.Pages),
		Limit: int32(result.Limit),
	}, nil
}
