package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/model"
)

// ObtenerOperaciones is the resolver for the obtenerOperaciones field.
func (r *queryResolver) ObtenerOperaciones(ctx context.Context, paginator *model.Paginator, filter *model.OperacionFilter) (*model.PaginatedOperacion, error) {
	panic(fmt.Errorf("not implemented: ObtenerOperaciones - obtenerOperaciones"))
}
