package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerPeriodosDisponibles is the resolver for the obtenerPeriodosDisponibles field.
func (r *queryResolver) ObtenerPeriodosDisponibles(ctx context.Context, anio *int32) ([]*model.PeriodoDisponible, error) {
	baseContext, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	disponibles, err := r.Administracion.Queries.ObtenerPeriodosDisponibles.Exec(
		baseContext,
		query.ObtenerPeriodosDisponiblesDTO{},
	)
	if err != nil {
		return nil, err
	}

	out := make([]*model.PeriodoDisponible, 0, len(disponibles))
	for _, d := range disponibles {
		periodo := d.Periodo()
		if anio != nil && int32(periodo.Anio()) != *anio {
			continue
		}
		mes := periodo.Mes()
		out = append(out, &model.PeriodoDisponible{
			Anio: int32(periodo.Anio()),
			Mes:  mes,
		})
	}

	return out, nil
}
