package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/model"
)

// Proveedor is the resolver for the proveedor field.
func (r *operacionResolver) Proveedor(ctx context.Context, obj *model.Operacion) (*string, error) {
	panic(fmt.Errorf("not implemented: Proveedor - proveedor"))
}

// Unidad is the resolver for the unidad field.
func (r *operacionResolver) Unidad(ctx context.Context, obj *model.Operacion) (*model.Unidad, error) {
	panic(fmt.Errorf("not implemented: Unidad - unidad"))
}

// Operacion returns OperacionResolver implementation.
func (r *Resolver) Operacion() OperacionResolver { return &operacionResolver{r} }

type operacionResolver struct{ *Resolver }
