package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/unidades/app/command"
)

// RegistrarSujeto is the resolver for the registrarSujeto field.
func (r *mutationResolver) RegistrarSujeto(ctx context.Context, input model.RegistrarSujetoDto) (model.Sujeto, error) {
	baseCtx, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	dto := command.RegistrarSujetoDTO{
		Tipo:               input.Tipo,
		DocumentoIdentidad: input.DocumentoIdentidad,
		Email:              input.Email,
		Telefono:           input.Telefono,
	}
	if input.Nombres != nil {
		dto.Nombres = *input.Nombres
	}
	if input.Apellidos != nil {
		dto.Apellidos = *input.Apellidos
	}
	if input.RazonSocial != nil {
		dto.RazonSocial = *input.RazonSocial
	}
	if input.Representante != nil {
		v := *input.Representante
		dto.RepresentanteID = &v
	}

	result, execErr := r.Unidades.Commands.RegistrarSujeto.Exec(baseCtx, dto)
	if execErr != nil {
		return nil, execErr
	}

	return model.SujetoFromDomain(result), nil
}
