package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/transacciones/app/command"
)

// TxRegistrarGasto is the resolver for the txRegistrarGasto field.
func (r *mutationResolver) TxRegistrarGasto(ctx context.Context, input model.RegistrarGastoInput) (bool, error) {
	adminCtx, err := corecontext.Wrap(ctx).AsAdmin()
	if err != nil {
		return false, err
	}

	tasaVal := 0
	if input.Tasa != nil {
		tasaVal = int(*input.Tasa)
	}

	_, err = r.Transacciones.Commands.RegistrarTransaccion.Exec(adminCtx, command.RegistrarTransaccionDTO{
		Tipo:         command.TipoGasto,
		Proveedor:    input.Proveedor,
		Concepto:     input.Concepto,
		Monto:        int(input.Monto),
		Moneda:       input.Moneda,
		Metodo:       input.Metodo,
		Tasa:         tasaVal,
		Fecha:        input.Fecha,
		Referencia:   input.Referencia,
		CuotaID:      &input.CuotaID,
		EsCondominio: input.EsCondominio,
	})

	if err != nil {
		return false, err
	}

	return true, nil
}
