package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/core/utils"
	"github.com/Sanaruca/condominio/internal/unidades/app/command"
)

// RegistrarUnidad is the resolver for the registrarUnidad field.
func (r *mutationResolver) RegistrarUnidad(ctx context.Context, input model.RegistrarUnidadDto) (*model.Unidad, error) {
	baseCtx, err := corecontext.Wrap(ctx).AsBase()
	if err != nil {
		return nil, err
	}

	dto := command.RegistrarUnidadDTO{
		Codigo:      input.Codigo,
		Estado:      input.Estado,
		Descripcion: utils.SafeStr(input.Descripcion),
	}
	if input.TitularPrimario != nil {
		v := *input.TitularPrimario
		dto.TitularPrimarioID = &v
	}
	if input.Contacto != nil {
		v := *input.Contacto
		dto.ContactoID = &v
	}

	result, execErr := r.Unidades.Commands.RegistrarUnidad.Exec(baseCtx, dto)
	if execErr != nil {
		return nil, execErr
	}

	return model.UnidadFromDomain(*result), nil
}
