package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/command"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/pagos/types/moneda"
)

// RegistrarGasto is the resolver for the registrarGasto field.
func (r *mutationResolver) RegistrarGasto(ctx context.Context, input model.RegistrarGastoDto) (*model.Gasto, error) {
	adminContext, err := corecontext.Wrap(ctx).AsAdmin()
	if err != nil {
		return nil, err
	}

	gasto, err := r.Administracion.Commands.RegistrarGasto.Exec(adminContext, command.RegistrarGastoDTO{
		GastoBase: command.GastoBase{
			Concepto: input.Concepo,
			Monto:    int(input.Monto),
			Moneda:   moneda.Moneda(input.Moneda),
			Fecha:    input.Fecha,
		},
		Proveedor: input.Proveedor,
	})

	if err != nil {
		return nil, err
	}

	return &model.Gasto{
		ID:            string(gasto.ID()),
		Proveedor:     gasto.Proveedor(),
		Monto:         int32(gasto.Monto()),
		Moneda:        string(gasto.Moneda()),
		Descripcion:   gasto.Descripcion(),
		Fecha:         gasto.Fecha(),
		Cuota:         new(string),
		Tasa:          int32(gasto.Tasa()),
		Total:         int32(gasto.Total()),
		Registro:      gasto.Audit().CreatedAt,
		RegistradoPor: gasto.Audit().CreatedBy,
	}, nil
}
