package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/model"
)

// RegistrarCuota is the resolver for the registrarCuota field.
func (r *mutationResolver) RegistrarCuota(ctx context.Context, input model.RegistrarCuotaDto) (model.CuotaType, error) {
	panic(fmt.Errorf("not implemented: RegistrarCuota - registrarCuota"))
}
