package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/finanzas/app/command"
	"github.com/Sanaruca/condominio/internal/unidades/models/unidad"
)

// RegistrarPago is the resolver for the registrarPago field.
func (r *mutationResolver) RegistrarPago(ctx context.Context, input *model.RegistrarPagoDto) (*model.Operacion, error) {
	admin, err := cc.Wrap(ctx).AsAdmin()

	if err != nil {
		return nil, err
	}

	if input.Concepto == nil {
		str := "Pago"
		input.Concepto = &str
	}

	operacion, err := r.Transacciones.Commands.RegistrarOperacion.Exec(admin, command.RegistrarTransaccionDTO{
		Tipo:         command.TipoPago,
		Unidad:       (*unidad.UnidadCodigo)(&input.Unidad),
		Proveedor:    nil,
		Concepto:     *input.Concepto,
		Monto:        int(input.Monto),
		Moneda:       input.Moneda,
		Metodo:       input.Metodo,
		Tasa:         int(input.Tasa),
		Fecha:        input.Fecha,
		Referencia:   input.Referencia,
		CuotaID:      nil,
		EsCondominio: false,
	})

	if err != nil {
		return nil, err
	}

	return &model.Operacion{
		ID:            operacion.ID(),
		Fecha:         operacion.Fecha(),
		Concepto:      operacion.Concepto(),
		Monto:         operacion.Monto().Float(),
		Moneda:        operacion.Moneda(),
		Metodo:        operacion.Metodo(),
		Tasa:          operacion.Tasa().Float(),
		Tipo:          operacion.Tipo(),
		Rol:           operacion.Rol(),
		Cuota:         operacion.CuotaID(),
		RegistradoPor: operacion.RegistradoPor(),
		Registro:      operacion.Fecha(),
		UnidadCodigo:  operacion.UnidadCodigo(),
		Proveedor:     operacion.ProveedorID(),
		// Unidad:
	}, nil
}
