package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
)

// RegistrarPagoADeuda is the resolver for the registrarPagoADeuda field.
// Deprecated: Usar el nuevo sistema de transacciones en su lugar.
func (r *mutationResolver) RegistrarPagoADeuda(ctx context.Context, pagoID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RegistrarPagoADeuda - registrarPagoADeuda"))
}
