package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/finanzas/models/transaccion"
)

// Monto is the resolver for the monto field.
func (r *movimientoAProveedorResolver) Monto(ctx context.Context, obj *transaccion.MovimientoAProveedor) (float64, error) {
	return obj.Monto().Float(), nil
}

// Cuota is the resolver for the cuota field.
func (r *movimientoAProveedorResolver) Cuota(ctx context.Context, obj *transaccion.MovimientoAProveedor) (*string, error) {
	panic(fmt.Errorf("not implemented: Cuota - cuota"))
}

// Proveedor is the resolver for the proveedor field.
func (r *movimientoAProveedorResolver) Proveedor(ctx context.Context, obj *transaccion.MovimientoAProveedor) (*model.Proveedor, error) {
	admin, err := cc.Wrap(ctx).AsAdmin()

	if err != nil {
		return nil, err
	}

	data, err := r.Administracion.Queries.ObtenerProveedor.Exec(admin, query.ObtenerProveedorDTO{ID: obj.Proveedor()})

	if err != nil {
		return nil, err
	}

	return model.ProveedorFromDomain(*data), nil
}

// MovimientoAProveedor returns MovimientoAProveedorResolver implementation.
func (r *Resolver) MovimientoAProveedor() MovimientoAProveedorResolver {
	return &movimientoAProveedorResolver{r}
}

type movimientoAProveedorResolver struct{ *Resolver }
