package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/core"
	"github.com/Sanaruca/condominio/internal/core/lib/logger"
	database "github.com/Sanaruca/condominio/internal/shared/adapters/gorm"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Titulares is the resolver for the titulares field.
func (r *unidadResolver) Titulares(ctx context.Context, obj *model.Unidad) ([]model.Titular, error) {
	rows, err := gorm.G[database.Titularidad](r.db).
		Where("unidad = ?", obj.ID).
		Joins(clause.LeftJoin.Association("Titular"), nil).
		Joins(clause.LeftJoin.Association("Titular.Representante"), nil).
		Find(ctx)

	if err != nil {
		return nil, err
	}

	titulares := make([]model.Titular, len(rows))

	for i, titulo := range rows {

		var titular model.Titular

		sujeto := titulo.Titular

		if sujeto.Tipo.PersonaNatural() {

			nombres := "Sin Nombre"
			apellidos := ""

			if sujeto.Nombres != nil && sujeto.Apellidos != nil {
				nombres = *sujeto.Nombres
				apellidos = *sujeto.Apellidos
			} else {
				logger.ErrorCtx(ctx, nil, "Persona sin nombre", "persona.nombre", sujeto.Nombres, "persona.apellidos", sujeto.Apellidos)
			}

			titular = model.Persona{
				ID:        sujeto.ID,
				Nombres:   nombres,
				Apellidos: apellidos,
				Email:     sujeto.Email,
				Telefono:  sujeto.Telefono,
				Cedula:    sujeto.DocumentoIdentidad,
				Registro:  sujeto.Registro,
				// TODO:
				// Actualizacion:  sujeto.Actualizacion,
				DisplayName: sujeto.DisplayName(),
			}
		} else if sujeto.Tipo.EnteJuridico() {

			representante := sujeto.Representante

			if representante == nil {
				logger.ErrorCtx(ctx, nil, "Representante de Ente no resuelto")
				return nil, core.ErrInternal
			}

			nombres := "Sin Nombre"
			apellidos := ""

			if sujeto.Nombres != nil && sujeto.Apellidos != nil {
				nombres = *sujeto.Nombres
				apellidos = *sujeto.Apellidos
			} else {
				logger.ErrorCtx(ctx, nil, "Representante sin nombre", "representante.nombre", representante.Nombres, "representante.apellidos", representante.Apellidos)
			}

			titular = model.Ente{
				ID:          sujeto.ID,
				RazonSocial: sujeto.DisplayName(),
				Email:       sujeto.Email,
				Telefono:    sujeto.Telefono,
				Cedula:      sujeto.DocumentoIdentidad,
				Representante: &model.Persona{
					ID:          representante.ID,
					Nombres:     nombres,
					Apellidos:   apellidos,
					Email:       representante.Email,
					Telefono:    representante.Telefono,
					Cedula:      representante.DocumentoIdentidad,
					Registro:    representante.Registro,
					DisplayName: representante.DisplayName(),
				},
				Registro:    sujeto.Registro,
				DisplayName: sujeto.DisplayName(),
			}

		} else {
			logger.ErrorCtx(ctx, nil, "No se pudo determinar el tipo de Sujeto")
			return nil, core.ErrInternal
		}

		//
		titulares[i] = titular

	}

	return titulares, nil
}

// Unidad returns UnidadResolver implementation.
func (r *Resolver) Unidad() UnidadResolver { return &unidadResolver{r} }

type unidadResolver struct{ *Resolver }
