interface Cuota {
  id: ID!
  monto: Float!
  mes: Int!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  recaudacion: Recaudacion!
}

type CuotaRegular implements Cuota {
  id: ID!
  monto: Float!
  mes: Int!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  recaudacion: Recaudacion!
}

type CuotaEspecial implements Cuota {
  id: ID!
  monto: Float!
  mes: Int!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  detalles: Proyecto!
  recaudacion: Recaudacion!
}

union CuotaType = CuotaRegular | CuotaEspecial

type PaginatedCuota {
  data: [CuotaType!]!
  total: Int!
  page: Int!
  pages: Int!
  limit: Int!
}
