// * Code generated by AI (Gemini/Assistant); DO NOT EDIT WITHOUT REVIEW.
// * This script was developed with AI assistance (Gemini) to automate
// * @autofilter injection in GraphQL schemas.
// * ⚠️ CAUTION: Review the regex patterns and file-handling logic to ensure
// * it correctly parses your .graphqls files without unintended side effects.
// *
// * Generated on: 2026-02-10
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Definimos el template como una constante para facilitar su edición
const injection_template = `
	# Code generated by tools/autofilter/autofilter.go
	and: [%[1]s!] # injected by @autofilter 
	or: [%[1]s!] # injected by @autofilter
	not: %[1]s # injected by @autofilter
`

func main() {
	project_root, err := findProjectRoot()

	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	err = filepath.Walk(project_root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}

		// Skip common large directories to improve performance
		if info.IsDir() {
			dirName := filepath.Base(path)
			switch dirName {
			case "node_modules", ".git", "vendor", "dist", "build", ".vscode", ".idea":
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".graphqls") {
			return nil
		}
		return injectFilters(path)
	})

	if err != nil {
		fmt.Printf("Error en el proceso: %v\n", err)
	}
}

func injectFilters(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	raw := string(content)
	if !strings.Contains(raw, "@autofilter") {
		return nil
	}

	// El regex captura:
	// 1. El nombre del input ($1)
	// 2. Todo el contenido hasta la llave de cierre ($2)
	re := regexp.MustCompile(`(?s)input\s+(\w+)\s+@autofilter\s*\{(.*?)\}`)

	newContent := re.ReplaceAllStringFunc(raw, func(match string) string {
		submatch := re.FindStringSubmatch(match)
		name := submatch[1]
		body := strings.TrimRight(submatch[2], " \n\t") // Limpiamos el final del cuerpo original

		if strings.Contains(body, "and:") {
			return match
		}

		fmt.Printf("✓ Aplicando template a: %s (%s)\n", path, name)

		// Construimos el nuevo cuerpo inyectando el template
		injected := fmt.Sprintf(injection_template, name)
		return fmt.Sprintf("input %s @autofilter {%s%s\n}", name, body, injected)
	})

	if newContent != raw {
		return os.WriteFile(path, []byte(newContent), 0644)
	}
	return nil
}

func findProjectRoot() (string, error) {
	curr, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(curr, "go.mod")); err == nil {
			return curr, nil
		}
		parent := filepath.Dir(curr)
		if parent == curr {
			return "", fmt.Errorf("go.mod no encontrado")
		}
		curr = parent
	}
}
