schema {
  query: Query
  mutation: Mutation
}

directive @autofilter on INPUT_OBJECT

"""
Directs the executor to defer this fragment when the `if` argument is true or undefined.
"""
directive @defer(
  """Deferred when true or undefined."""
  if: Boolean = true
  """Unique name"""
  label: String
) on FRAGMENT_SPREAD | INLINE_FRAGMENT

directive @paginable on OBJECT

type Abono {
  fecha: DateTime!
  monto: Float!
  pago: ID!
}

input BooleanCondition {
  eq: Boolean
}

interface Cuota {
  actualizacion: DateTime!
  anio: Int!
  id: ID!
  mes: Mes!
  monto: Float!
  recaudacion: Recaudacion!
  registro: DateTime!
}

type CuotaEspecial implements Cuota {
  actualizacion: DateTime!
  anio: Int!
  detalles: Proyecto!
  id: ID!
  mes: Mes!
  monto: Float!
  recaudacion: Recaudacion!
  registro: DateTime!
}

input CuotaFilter {
  and: [CuotaFilter!]
  id: StringCondition
  monto: IntCondition
  not: CuotaFilter
  or: [CuotaFilter!]
}

type CuotaRegular implements Cuota {
  actualizacion: DateTime!
  anio: Int!
  id: ID!
  mes: Mes!
  monto: Float!
  recaudacion: Recaudacion!
  registro: DateTime!
}

union CuotaType = CuotaEspecial | CuotaRegular

scalar DateTime

type Deuda {
  abonos: [Abono!]
  cuota: ID!
  deuda: Float!
  estado: EstadoDeDeuda!
  id: String!
  monto: Float!
  registro: DateTime!
  unidad: ID!
}

type Ente implements Sujeto {
  actualizacion: DateTime!
  cedula: String!
  email: String!
  id: String!
  razon_social: String!
  registro: DateTime!
  representante: Persona!
  telefono: String!
}

enum EstadoDeDeuda {
  ABONADA
  PENDIENTE
  SALDADA
}

enum EstadoDeProyecto {
  ACTIVO
  BORRADOR
  CERRADO
}

enum EstadoDeUnidad {
  ACTIVA
  EN_LITIGIO
  EXENTA
  INHABITADA
  PREVENTA
  SUSPENDIDA
}

input IntCondition {
  eq: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
}

type LoginCredentialsDTO {
  token: String!
}

enum Mes {
  ABRIL
  AGOSTO
  DICIEMBRE
  ENERO
  FEBRERO
  JULIO
  JUNIO
  MARZO
  MAYO
  NOVIEMBRE
  OCTUBRE
  SEPTIEMBRE
}

enum MetodoDeTransaccion {
  Cheque
  Compensacion
  Efectivo
  PagoMovil
  TransferenciaInternacional
  TransferenciaNacional
}

enum Moneda {
  USD
  VED
}

interface Movimiento {
  cuota: ID
  id: String!
  monto: Float!
  tipo: TipoDeMovimiento!
}

type MovimientoACondominio implements Movimiento {
  cuota: ID
  id: String!
  monto: Float!
  tipo: TipoDeMovimiento!
}

type MovimientoAProveedor implements Movimiento {
  cuota: ID
  id: String!
  monto: Float!
  proveedor: Proveedor!
  tipo: TipoDeMovimiento!
}

type MovimientoAUnidad implements Movimiento {
  cuota: ID
  id: String!
  monto: Float!
  tipo: TipoDeMovimiento!
  unidad: Unidad!
}

union MovimientoType = MovimientoACondominio | MovimientoAProveedor | MovimientoAUnidad

type Mutation {
  _empty: String
  login(email: String!, password: String!): LoginCredentialsDTO!
  registrarCuota(input: RegistrarCuotaDTO!): CuotaType!
  registrarGasto(input: RegistrarGastoDTO!): Transaccion
}

input ObtenerProveedoresDTO {
  and: [ObtenerProveedoresDTO!]
  id: StringCondition
  not: ObtenerProveedoresDTO
  or: [ObtenerProveedoresDTO!]
}

type PaginatedCuota {
  data: [CuotaType!]!
  limit: Int!
  page: Int!
  pages: Int!
  total: Int!
}

type PaginatedDeuda {
  data: [Deuda!]!
  limit: Int!
  page: Int!
  pages: Int!
  total: Int!
}

type PaginatedTransaccion {
  data: [Transaccion!]!
  limit: Int!
  page: Int!
  pages: Int!
  total: Int!
}

type PaginatedUnidad {
  data: [Unidad!]!
  limit: Int!
  page: Int!
  pages: Int!
  total: Int!
}

input Paginator {
  limit: Int!
  page: Int!
}

type Persona implements Sujeto {
  actualizacion: DateTime!
  apellidos: String!
  cedula: String!
  email: String!
  id: String!
  nombres: String!
  registro: DateTime!
  telefono: String!
}

type Proveedor {
  actualizado_en: DateTime!
  creado_en: DateTime!
  direccion: String
  email: String
  id: ID!
  nombre: String!
  rif: String!
  telefono: String
}

type Proyecto {
  actualizacion: DateTime!
  descripcion: String!
  estado: EstadoDeProyecto!
  fecha_limite: DateTime!
  interes_por_mora: Float!
  justificacion: String!
  registro: DateTime!
  titulo: String!
}

type Query {
  _empty: String
  obtenerCuota(id: String!): CuotaType
  obtenerCuotas(filter: CuotaFilter, paginator: Paginator): PaginatedCuota!
  obtenerDeudasDeUnaUnidad(id: ID!, paginator: Paginator): PaginatedDeuda!
  obtenerDeudasDeUnaUnidadPorCodigo(codigo: String!, paginator: Paginator): PaginatedDeuda!
  obtenerMovimientos(filter: TransaccionFilter, paginator: Paginator, tipo: TipoDeMovimiento): PaginatedTransaccion!
  obtenerProveedores(filter: ObtenerProveedoresDTO): [Proveedor!]!
  obtenerTasa(anio: Int, dia: Int, mes: Mes): Tasa!
  obtenerUnidad(id: ID!): Unidad
  obtenerUnidadPorCodigo(codigo: String!): Unidad
  obtenerUnidades(filter: UnidadFilter, paginator: Paginator): PaginatedUnidad
  obtenerUnidadesEstadisticas: UnidadesTotales
}

type Recaudacion {
  moneda: Moneda!
  monto_estimado: Float!
  monto_pendiente: Float!
  monto_recaudado: Float!
  pagos_asociados: Int!
  unidades: Int!
  unidades_aplicadas: Int!
  unidades_pendientes: Int!
  unidades_solventes: Int!
}

input RegistrarCuotaDTO {
  anio: Int
  descripcion: String
  fecha_limite: DateTime
  gastos: [ID!]!
  justificacion: String
  mes: Mes
  tipo: TipoDeCuota!
  titulo: String
}

input RegistrarGastoDTO {
  consepto: String!
  fecha: DateTime
  metodo: MetodoDeTransaccion!
  moneda: Moneda
  monto: Int!
  proveedor: ID!
  referencia: String
  tasa: Int!
}

input RegistrarProveedorDTO {
  direccion: String
  email: String!
  nombre: String!
  rif: String!
  telefono: String!
}

input StringCondition {
  eq: String
  in: [String]
  like: String
  regex: String
}

interface Sujeto {
  actualizacion: DateTime!
  cedula: String!
  email: String!
  id: String!
  registro: DateTime!
  telefono: String!
}

type Tasa {
  fecha: String!
  fuente: String!
  moneda: String!
  tipo: String!
  valor: Float!
}

enum TipoDeCuota {
  Especial
  Regular
  Semilla
}

enum TipoDeMovimiento {
  Credito
  Debito
}

union Titular = Ente | Persona

type Transaccion {
  concepto: String!
  fecha: DateTime!
  id: String!
  metodo: MetodoDeTransaccion!
  moneda: Moneda!
  monto_total: Float!
  movimientos: [MovimientoType!]!
  registrado_por: String!
  registro: DateTime!
  tasa: Float!
}

input TransaccionFilter {
  and: [TransaccionFilter!]
  concepto: StringCondition
  cuota_id: StringCondition
  not: TransaccionFilter
  or: [TransaccionFilter!]
}

type Unidad {
  codigo: String!
  contacto: Persona
  deuda: Float!
  estado: EstadoDeUnidad!
  id: String!
  titular_primario: Titular
  wallet: Float!
}

input UnidadFilter {
  and: [UnidadFilter!]
  codigo: StringCondition
  estado: StringCondition
  id: StringCondition
  not: UnidadFilter
  or: [UnidadFilter!]
}

type UnidadesTotales {
  total_asignado: Float!
  total_pendiente: Float!
  total_unidades: Int!
  unidades_activas: Int!
  unidades_con_pendientes: Int!
  unidades_en_litigio: Int!
  unidades_exentas: Int!
  unidades_inhabitadas: Int!
  unidades_preventa: Int!
  unidades_solventes: Int!
  unidades_suspendidas: Int!
}