schema {
  query: Query
  mutation: Mutation
}

directive @autofilter on INPUT_OBJECT

"""
Directs the executor to defer this fragment when the `if` argument is true or undefined.
"""
directive @defer(
  """Deferred when true or undefined."""
  if: Boolean = true
  """Unique name"""
  label: String
) on FRAGMENT_SPREAD | INLINE_FRAGMENT

input BooleanCondition {
  eq: Boolean
}

type Cuota {
  actualizacion: DateTime!
  anio: Int!
  id: ID!
  mes: Int!
  monto: Int!
  registro: DateTime!
}

input CuotaFilter {
  and: [CuotaFilter!]
  id: StringCondition
  monto: IntCondition
  not: CuotaFilter
  or: [CuotaFilter!]
}

scalar DateTime

type Gasto {
  actualizacion: DateTime!
  actualizado_por: String!
  cuota: ID
  descripcion: String
  fecha: DateTime!
  id: ID!
  moneda: String!
  monto: Int!
  proveedor: String!
  registrado_por: String!
  registro: DateTime!
  tasa: Int!
  total: Int!
}

input IntCondition {
  eq: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
}

type LoginCredentialsDTO {
  token: String!
}

enum MetodoDePago {
  Efectivo
  PagoMovil
  Transferencia
}

enum Moneda {
  USD
  VED
}

type Mutation {
  _empty: String
  login(email: String!, password: String!): LoginCredentialsDTO!
  registrarPago(input: RegistrarPagoDTO!): Boolean!
}

union Paginable = Cuota | Gasto

type Paginated {
  data: [Paginable!]!
  limit: Int!
  page: Int!
  pages: Int!
  total: Int!
}

input Paginator {
  limit: Int!
  page: Int!
}

type Pago {
  actualizacion: DateTime!
  actualizado_por: String!
  cuenta: Int!
  destinado: Int!
  fecha: DateTime!
  id: String!
  metodo: MetodoDePago!
  moneda: Moneda!
  monto: Int!
  referencia: String!
  registrado_por: String!
  registro: DateTime!
  tasa: Int!
  villa: Int!
}

type Proveedor {
  actualizado_en: DateTime!
  creado_en: DateTime!
  direccion: String
  email: String
  id: ID!
  nombre: String!
  rif: String!
  telefono: String
  tipo: String!
}

type Query {
  _empty: String
  obtenerCuotas(filter: CuotaFilter, paginator: Paginator): Paginated!
  obtenerProveedores: [Proveedor!]!
}

input RegistrarPagoDTO {
  fecha: DateTime
  metodo: MetodoDePago!
  moneda: Moneda!
  monto: Int!
  referencia: String!
  tasa: Int!
  villa: Int!
}

input StringCondition {
  eq: String
  in: [String]
  like: String
  regex: String
}

enum TipoDeCuota {
  Especial
  Regular
  Semilla
}